import { MetadataRoute } from "next";
import { getAllSlugs } from "@/lib/blog";
import CONTENT_DATES from "@/data/content-dates.json";

const BASE = process.env.NEXT_PUBLIC_SITE_URL || "https://learn.chparenting.com";

// Real per-page content dates, regenerated by scripts/generate-content-dates.mjs
// on every build. Emitting `new Date()` here instead would stamp all ~350 URLs
// with one build time, which Google discards as an unreliable lastmod.
const DATES = CONTENT_DATES as Record<string, string>;
const FALLBACK = new Date("2026-03-05T00:00:00Z");

function lm(routePath: string): Date {
  const iso = DATES[routePath];
  return iso ? new Date(iso) : FALLBACK;
}

/** Sitemap entry for a route path (e.g. "/elementary/unit/3"). */
function entry(
  routePath: string,
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"],
  priority: number,
) {
  return {
    url: routePath === "/" ? BASE : `${BASE}${routePath}`,
    lastModified: lm(routePath),
    changeFrequency,
    priority,
  };
}

function unitIds(count: number) {
  return Array.from({ length: count }, (_, i) => i + 1);
}

function levelPages(level: string, unitCount: number, priority: number) {
  return [
    entry(`/${level}`, "weekly", priority),
    ...unitIds(unitCount).map(id => entry(`/${level}/unit/${id}`, "monthly", priority - 0.1)),
    entry(`/${level}/game`, "monthly", priority - 0.1),
    entry(`/${level}/speaking`, "monthly", priority - 0.1),
    entry(`/${level}/mock-test`, "monthly", priority - 0.1),
    entry(`/${level}/writing`, "monthly", priority - 0.1),
  ];
}

const BOARD_GAMES = [
  "pattern-master", "mini-sudoku", "sequence-quest",
  "code-path", "logic-gates", "loop-builder",
  "memory-match", "memory-sequence",
  "color-tap", "whack-a-mole",
  "math-rush", "speed-sort",
  "word-chain", "word-search",
  "maze-runner", "emoji-puzzle",
  "go-game", "chinese-checkers",
];

const MATH_TOPICS = [
  "basic-arithmetic", "fractions", "decimals", "percentages",
  "geometry", "intro-algebra", "word-problems", "time-measurement",
];

const FINANCE_MODULES = [
  "money-basics", "needs-vs-wants", "savings-calculator",
  "allowance-budget", "red-envelope", "expense-tracker",
];

// 與各 section page.tsx 的 generateStaticParams 同步
const CHINESE_TOPICS: [string, string[]][] = [
  ["lower", ["zhuyin", "characters", "vocabulary", "reading"]],
  ["middle", ["idioms", "reading", "writing"]],
  ["high", ["idioms", "reading", "grammar"]],
];
const HISTGEO_TOPICS: [string, string[]][] = [
  ["taiwan", ["taiwan-history", "taiwan-geography", "taiwan-culture"]],
  ["asia", ["asia-history", "asia-geography"]],
  ["world", ["world-history", "world-geography", "world-culture"]],
];
const MUSIC_TOPICS: [string, string[]][] = [
  ["intro", ["notes", "rhythm", "pitch"]],
  ["basic", ["scales", "intervals", "dynamics"]],
  ["advanced", ["chords", "form", "knowledge"]],
];

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    // Platform pages
    entry("/", "monthly", 1),
    entry("/about", "monthly", 0.5),
    entry("/how-to-use", "monthly", 0.6),
    entry("/faq", "monthly", 0.6),
    entry("/achievements", "monthly", 0.5),
    entry("/exam-info", "monthly", 0.7),
    entry("/parent-guide", "monthly", 0.6),

    // Blog
    entry("/blog", "weekly", 0.7),
    ...getAllSlugs().map(slug => entry(`/blog/${slug}`, "weekly", 0.7)),

    // GEPT levels
    ...levelPages("elementary", 20, 0.9),
    ...levelPages("intermediate", 34, 0.8),
    ...levelPages("upper-intermediate", 40, 0.8),

    // JLPT levels
    ...levelPages("jlpt-n5", 20, 0.8),
    entry("/jlpt-n5/gojuon", "monthly", 0.7),
    ...levelPages("jlpt-n4", 20, 0.8),
    ...levelPages("jlpt-n3", 20, 0.8),
    ...levelPages("jlpt-n2", 20, 0.7),
    ...levelPages("jlpt-n1", 20, 0.7),

    // Board games
    entry("/board-games", "monthly", 0.7),
    ...BOARD_GAMES.map(id => entry(`/board-games/${id}`, "monthly", 0.6)),

    // Typing game
    entry("/typing-game", "monthly", 0.7),

    // Math section
    entry("/math", "weekly", 0.8),
    ...MATH_TOPICS.map(id => entry(`/math/${id}`, "monthly", 0.7)),

    // Finance section
    entry("/finance", "weekly", 0.8),
    ...FINANCE_MODULES.map(id => entry(`/finance/${id}`, "monthly", 0.7)),

    // Chinese language section
    entry("/chinese-lang", "weekly", 0.8),
    ...CHINESE_TOPICS.flatMap(([grade, topics]) => [
      entry(`/chinese-lang/${grade}`, "monthly", 0.7),
      ...topics.map(t => entry(`/chinese-lang/${grade}/${t}`, "monthly", 0.6)),
    ]),

    // History & geography section
    entry("/history-geo", "weekly", 0.8),
    ...HISTGEO_TOPICS.flatMap(([region, topics]) => [
      entry(`/history-geo/${region}`, "monthly", 0.7),
      ...topics.map(t => entry(`/history-geo/${region}/${t}`, "monthly", 0.6)),
    ]),

    // Music section
    entry("/music", "weekly", 0.8),
    ...MUSIC_TOPICS.flatMap(([level, topics]) => [
      entry(`/music/${level}`, "monthly", 0.7),
      ...topics.map(t => entry(`/music/${level}/${t}`, "monthly", 0.6)),
    ]),
  ];
}
